FROM node:26.8.1-alpine AS build
WORKDIR /ui
COPY ui/package.json ui/package-lock.json* ./
RUN npm install --ignore-scripts
COPY ui ./
RUN npm run build

FROM nginx:1.31.4-alpine
ARG CADASTRE_SOURCE_REVISION=unknown
ARG CADASTRE_SCHEMA_VERSION=1
ARG CADASTRE_VERSION=unknown
LABEL org.opencontainers.image.title="Cadastre GUI" \
      org.opencontainers.image.source="https://github.com/TheDancingDeveloper-org/cadastre" \
      org.opencontainers.image.version="$CADASTRE_VERSION" \
      org.opencontainers.image.revision="$CADASTRE_SOURCE_REVISION" \
      io.cadastre.schema-version="$CADASTRE_SCHEMA_VERSION"
RUN apk add --no-cache gettext
COPY --from=build /ui/dist /usr/share/nginx/html
COPY ui/nginx.conf /etc/nginx/conf.d/default.conf
COPY ui/runtime-config.template.js /usr/share/nginx/html/runtime-config.template.js
RUN printf '#!/bin/sh\nenvsubst '\''${CADASTRE_API_ORIGIN}'\'' < /usr/share/nginx/html/runtime-config.template.js > /tmp/runtime-config.js\n' > /docker-entrypoint.d/40-cadastre-config.sh \
 && chmod +x /docker-entrypoint.d/40-cadastre-config.sh
EXPOSE 8080
