"""The checked-in browser contract must be generated from OpenAPI."""

import subprocess
import sys
from pathlib import Path

from cadastre.adapters.http import openapi_schema


def test_gui_types_are_generated_from_every_openapi_path() -> None:
    root = Path(__file__).parents[1]
    generated = (root / "ui/src/api/generated.ts").read_text(encoding="utf-8")
    for path in openapi_schema()["paths"]:
        assert f'"{path}"' in generated


def test_gui_type_generator_is_deterministic() -> None:
    root = Path(__file__).parents[1]
    subprocess.run(
        [sys.executable, "scripts/generate-gui-types.py"],
        cwd=root,
        check=True,
    )
    assert "Generated by scripts/generate-gui-types.py" in (
        root / "ui/src/api/generated.ts"
    ).read_text(encoding="utf-8")


def test_gui_has_generated_client_contract_tests() -> None:
    content = (Path(__file__).parents[1] / "ui/tests/client.test.ts").read_text()
    assert "typed operations" in content
    assert "structured API errors" in content
