#!/usr/bin/env python3
"""Generate the checked-in TypeScript API contract from OpenAPI metadata."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cadastre.adapters.http import openapi_schema  # noqa: E402

TARGET = ROOT / "ui" / "src" / "api" / "generated.ts"


def main() -> None:
    # `manifest_enabled=True` so the checked-in TypeScript contract names the
    # full possible API surface, matching how auth-gated write routes are
    # already listed unconditionally — the runtime document defaults to
    # False and only advertises /manifest/* when the catalog enables it.
    document = openapi_schema(manifest_enabled=True)
    routes = sorted(document["paths"])
    route_union = " | ".join(json.dumps(route) for route in routes)
    provenance_type = (
        "export type Provenance = {"
        " source: string; as_of: string | null; stale?: boolean; trust?: string };\n"
    )
    document_type = (
        "export type Document = {"
        " command: string; result: unknown; provenance?: Provenance[];"
        " stale?: string[]; [key: string]: unknown };\n"
    )
    output = "".join(
        [
            "// Generated by scripts/generate-gui-types.py; do not edit by hand.\n",
            provenance_type,
            document_type,
            "export type ApiError = { error: { kind: string; message: string } };\n",
            f"export type ApiRoute = {route_union};\n",
            'export type HttpMethod = "GET" | "POST";\n',
            "export type OpenApiDocument = { openapi: string; "
            "paths: Record<ApiRoute, unknown> };\n",
        ]
    )
    TARGET.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
